### ISSUE TITLE
The current version, the video processing error at the beginning .

### ISSUE THREAD

**Issue by jasudev** [BradLarson/GPUImage#1276]
In the current version, an error will occur.
In August, but the downloaded version did not have this problem.
What problem?

The link below is a problem SimpleVideoFileFilter project file.
http://www.ifacies.com/test/SimpleVideoFileFilter.zip

Error message :
2013-10-24 03:46:44.264 SimpleVideoFileFilter[8738:60b] Application windows are expected to have a root view controller at the end of application launch
2013-10-24 03:46:44.426 SimpleVideoFileFilter[8738:1603] **\* Assertion failure in -[GPUImageMovieWriter createDataFBO], /Users/jasu/Dropbox/iPhoneDevelop/DEVELOP_PROJECT/GlassMov_PROJECT/framework/GPUImage-master22/framework/Source/iOS/GPUImageMovieWriter.m:548
2013-10-24 03:46:44.446 SimpleVideoFileFilter[8738:1603] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Incomplete filter FBO: 36055'
**\* First throw call stack:
(0x30fdde8b 0x3b2d86c7 0x30fddd5d 0x3198623f 0x31aff 0x31dd7 0x31ec9 0x3236d 0xfcd7 0x11ebf 0x2725b 0x26a13 0x26761 0x3b7c18fb 0x1ca8b 0x265e3 0x25aaf 0x3103b 0x2fe26a1f 0x3b7bd103 0x3b7c1e77 0x3b7bef9b 0x3b7c2751 0x3b7c29d1 0x3b8ecdff 0x3b8eccc4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by EstebanVallejo** [comment]
Got this issue fixed with @dovtuan solution .

code example:
  importedMovieWriter.shouldPassthroughAudio = YES;
  importedMovie.audioEncodingTarget = [videoAsset hasAudioTrack] ? importedMovieWriter : nil;
  [importedMovie enableSynchronizedEncodingUsingMovieWriter:importedMovieWriter];

  [importedMovieWriter startRecording];
  [importedMovie startProcessing];

BTW: I extended AVAsset and added some utility methods like "hasAudioTrack" , but you can do that the old way.

**Comment by kylebrowning** [comment]
This is still an issue. 
If i disable audio, it works fine, but that isn't an option.

**Comment by melvynhills** [comment]
@kylebrowning did you find a fix for this?

**Comment by kylebrowning** [comment]
Nope

**Comment by melvynhills** [comment]
@kylebrowning I just fixed it by using the master branch of the repo. I was using a [branch of mine](https://github.com/melvynhills/GPUImage/commit/0f94cbbbc1936759f3d6895fb0e9d92ec7b133e2) to fix black frames at the beginning of the video...

**Comment by aiyub007** [comment]
Great @dovtuan

**Comment by yao2030** [comment]
Also encountered the same problem, 
![d3ba24c7-2905-4dfe-8319-cea64328c734](https://cloud.githubusercontent.com/assets/1877053/21599511/92e4b96c-d1a8-11e6-904f-9b5a15182884.png)
![91bfc075-b6a6-4a66-ac68-cfdbcde38e12](https://cloud.githubusercontent.com/assets/1877053/21599517/a65fa286-d1a8-11e6-8181-95883e7145bf.png)

**Comment by ramanihiteshc** [comment]
// this line add solve your problm 
 _movieFile.audioEncodingTarget = nil;
importedMovieWriter.shouldPassthroughAudio = YES

**Comment by HQL-yunyunyun** [comment]
I have the same issues, but ` _movieFile.audioEncodingTarget = nil;` do not fix my isuss because in my case `AudioTrack.count > 0`.
 And i found the reason is : 
* `[assetWriterAudioInput markAsFinish]`had call before `[GPUImageMovieWriter createDataFBO]`, so lead to assetWriter.status == failing,` [assetWriterPixelBufferInput pixelBufferPool]` return NULL,And *renderTarget* create failed.
so we just ensure `[GPUImageMovieWriter createDataFBO]` call after `[assetWriterAudioInput markAsFinish]` this bug will be fix.
In my case, i inherit *GPUImageMoveiWriter* and rewrite `enableSynchronizationCallbacks` method:
```
#import "GCImageMovieWriter.h"
#import <GPUImage/GPUImage.h>

@implementation GCImageMovieWriter {
    BOOL videoBeganEncoding, videoEncodingIsFinished, audioEncodingIsFinished;
    dispatch_queue_t audioQueue, videoQueue;
}

@synthesize videoInputReadyCallback;
@synthesize audioInputReadyCallback;
@synthesize paused = _paused;

- (void)enableSynchronizationCallbacks {
    ///!!!: 修复音频轨没有数据的bug
    // https://github.com/BradLarson/GPUImage/issues/1276
    videoBeganEncoding = NO;
    if (videoInputReadyCallback != NULL)
    {
        if( assetWriter.status != AVAssetWriterStatusWriting )
        {
            [assetWriter startWriting];
        }
        videoQueue = dispatch_queue_create("com.sunsetlakesoftware.GPUImage.videoReadingQueue", NULL);
        [assetWriterVideoInput requestMediaDataWhenReadyOnQueue:videoQueue usingBlock:^{
            if( _paused )
            {
                //NSLog(@"video requestMediaDataWhenReadyOnQueue paused");
                // if we don't sleep, we'll get called back almost immediately, chewing up CPU
                usleep(10000);
                return;
            }
            //NSLog(@"video requestMediaDataWhenReadyOnQueue begin");
            while( assetWriterVideoInput.readyForMoreMediaData && ! _paused )
            {
                BOOL hasVideoEncoding = videoInputReadyCallback();
                if (hasVideoEncoding) {
                    videoBeganEncoding = YES;
                }
                if( videoInputReadyCallback && ! hasVideoEncoding && ! videoEncodingIsFinished )
                {
                    runAsynchronouslyOnContextQueue(_movieWriterContext, ^{
                        if( assetWriter.status == AVAssetWriterStatusWriting && ! videoEncodingIsFinished )
                        {
                            videoEncodingIsFinished = YES;
                            [assetWriterVideoInput markAsFinished];
                        }
                    });
                }
            }
            //NSLog(@"video requestMediaDataWhenReadyOnQueue end");
        }];
    }
    
    if (audioInputReadyCallback != NULL)
    {
        audioQueue = dispatch_queue_create("com.sunsetlakesoftware.GPUImage.audioReadingQueue", NULL);
        [assetWriterAudioInput requestMediaDataWhenReadyOnQueue:audioQueue usingBlock:^{
            if( _paused )
            {
                //NSLog(@"audio requestMediaDataWhenReadyOnQueue paused");
                // if we don't sleep, we'll get called back almost immediately, chewing up CPU
                usleep(10000);
                return;
            }
            //NSLog(@"audio requestMediaDataWhenReadyOnQueue begin");
            while( assetWriterAudioInput.readyForMoreMediaData && ! _paused )
            {
                if( audioInputReadyCallback && ! audioInputReadyCallback() && ! audioEncodingIsFinished )
                {
                    runAsynchronouslyOnContextQueue(_movieWriterContext, ^{
                        if( assetWriter.status == AVAssetWriterStatusWriting && ! audioEncodingIsFinished && videoBeganEncoding )
                        {
                            audioEncodingIsFinished = YES;
                            [assetWriterAudioInput markAsFinished];
                        }
                    });
                }
            }
            //NSLog(@"audio requestMediaDataWhenReadyOnQueue end");
        }];
    }   
}
@end
```
blog:
https://hql-yunyunyun.github.io/GPUImage-Incomplete-filter-FBO-36055-bug修复记录/
